#include <algorithm>
#include <cassert>
#include <chrono>
#include <climits>
#include <deque>
#include <fstream>
#include <iostream>
#include <queue>
#include <random>
#include <sstream>
#include <numeric>
#include <map>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <iomanip>
using namespace std;
